main: fun.sunrisemc.commandscheduler.CommandSchedulerPlugin
name: CommandScheduler
description: Schedule commands to run at specific points.
author: TheFishNextDoor
version: ${project.version}
api-version: 1.18
commands:
  commandscheduler:
    description: Main plugin command.
    usage: /commandscheduler [subcommand]
    permission: commandscheduler
    aliases: [cs, cmdscheduler, cmdsched, scheduler, sched]
permissions:
  commandscheduler.reload:
    description: Allows use of /commandscheduler reload.
  commandscheduler.view:
    description: Allows use of /commandscheduler view.
  commandscheduler.execute:
    description: Allows use of /commandscheduler execute.
  commandscheduler.time:
    description: Allows use of /commandscheduler time.