name: CommandSchedular
main: fun.sunrisemc.template.CommandSchedularPlugin
version: 1.0.0
api-version: 1.18
author: TheFishNextDoor
description: Allows the scheduling of commands.
commands:
  commandschedular:
    description: Main plugin command
    usage: /commandschedular [subcommand]
    permission: commandschedular
    aliases: [cs, cmdschedular, cmdsched, schedular, sched]
permissions:
  commandschedular.reload:
    description: Allows use of /commandschedular reload
  commandschedular.execute:
    description: Allows use of /commandschedular execute