name: CommandSchedular
main: fun.sunrisemc.commandschedular.CommandSchedularPlugin
version: 1.2.1
api-version: 1.18
author: TheFishNextDoor
description: Schedule commands to run at specific points.
commands:
  commandschedular:
    description: Main plugin command.
    usage: /commandschedular [subcommand]
    permission: commandschedular
    aliases: [cs, cmdschedular, cmdsched, schedular, sched]
permissions:
  commandschedular.reload:
    description: Allows use of /commandschedular reload.
  commandschedular.execute:
    description: Allows use of /commandschedular execute.
  commandschedular.time:
    description: Allows use of /commandschedular time.